name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install python-semantic-release

      - name: Release semantically
        run: |
            git config --global user.name "${COMMITER_NAME}"
            git config --global user.email "${COMMITER_EMAIL}"
            python -m semantic_release.cli publish -v DEBUG \
                -D commit_author="${COMMITER_NAME} <{$COMMITER_EMAIL}>"
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            COMMITER_NAME: github-actions
            COMMITER_EMAIL: action@github.com

      - name: Upload to JYPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.JYPI_UPLOAD_USER }}
          password: ${{ secrets.JYPI_UPLOAD_PASSWORD }}
          repository_url: ${{ secrets.JYPI }}
          verbose: true
