name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release

      - name: Release semantically
        run: |
          export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          python -m semantic_release.cli publish -v DEBUG \
              -D commit_author="github-actions <action@github.com>"

