name: release semantically

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Test 1
        if: ${{ github.event_name == 'push' }}
        run: |
          echo WORKS

      - name: Test 2
        if: ${{ github.event_name == 'push' }}
        run: |
          false

      - name: Test 3
        if: always()
        run: |
          echo WORKS
