name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install twine

      - name: Release semantically
        run: |
            git config --global user.name "JUST ADD AI"
            git config --global user.email "jaai@justadd.ai"
            python -m semantic_release.cli publish -v DEBUG \
                -D commit_author="JUST ADD AI <jaai@justadd.ai>"
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to JYPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.JYPI_UPLOAD_USER }}
          password: ${{ secrets.JYPI_UPLOAD_PASSWORD }}
          repository_url: ${{ secrets.JYPI }}
          verbose: true
