name: tag latest

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: Check for existing tag
      #   run: |
      #     [ ! -z ] && echo Tag already exist  && false

      - name: Build
        run: |
          echo This should run if the current commit is not already tagged

      # should tag the current commit because the build ran and the commit wasn't already tagged
      - name: Tag
        run: |
          [ -z "`git tag -l nightly`" ] && git tag -d nightly
          git tag nightly
          git push origin nightly
