name: tag latest

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      conclusion: ${{ steps.tag.outputs.conclusion }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: tag
        name: Check if tag already exists at the current commit
        run: |
          echo ::set-output name=conclusion::success
          if [ ! -z "`git tag -l Nightly`" ]; then
            sha=`git rev-parse Nightly`
            if [ "$sha" == "${{ github.sha }}" ]; then
              echo "Tag already exists on the commit that triggered this workflow."
              echo ::set-output name=conclusion::failure
            fi
          fi

  build_and_tag:
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.output.conclusion == 'success'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: |
          echo This should run if the current commit is not already tagged

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Nightly
          body: Latest nightly build.
          prerelease: true
