name: tag latest

on:
  schedule:
    - cron: '40 0 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: check_tag
        name: Check if tag already exists at the current commit
        run: |
          if [ ! -z "`git tag -l nightly`" ]; then
            sha=`git rev-parse nightly`
            if [ "$sha" == "${{ github.sha }}" ]; then
              echo "Tag already exists on the commit that triggered this workflow."
              exit -1
            fi
          fi

  build_and_tag:
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.result == 'success'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: |
          echo This should run if the current commit is not already tagged

      # should tag the current commit because the build ran and the commit wasn't already tagged
      - name: Tag
        run: |
          [ ! -z "`git tag -l nightly`" ] && git tag -d nightly
          git tag nightly
          git push origin nightly
