name: tag latest

on:
  schedule:
    - cron: '1 * * * *'


jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      conclusion: ${{ steps.tag.outputs.conclusion }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: tag
        name: Check if tag already exists at the current commit
        run: |
          if [ ! -z "`git tag -l nightly`" ]; then
            sha=`git rev-parse nightly`
            if [ "$sha" == "${{ github.sha }}" ]; then
              echo "Tag already exists on the commit that triggered this workflow."
              echo ::set-output name=conclusion::failure
            fi
          fi
          echo ::set-output name=conclusion::success

  build_and_tag:
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.output.conclusion == 'success'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: |
          echo This should run if the current commit is not already tagged

      # should tag the current commit because the build ran and the commit wasn't already tagged
      - name: Tag
        run: |
          [ ! -z "`git tag -l nightly`" ] && git tag -d nightly && git push --delete origin nightly
          git tag nightly
          git push origin nightly
